In [3]:
# stage11
import numpy as np
from steps.step11 import Variable, Add

xs =[Variable(np.array(1.0)), Variable(np.array(2.0))]
f = Add()
ys = f(xs)
y = ys[0]
print(y.data)

3.0


In [8]:
# step12
# 12.1
import numpy as np
from steps.step12 import Variable, Add

x0 = Variable(np.array(1.0))
x1 = Variable(np.array(2.0))
f = Add()
y = f(x0, x1)
print(y.data)

3.0


In [1]:
# 12.3
import numpy as np
from steps.step12 import Variable, add
x0 = Variable(np.array(1.0))
x1 = Variable(np.array(2.0))
y = add(x0, x1)
print(y.data)

3.0


In [1]:
# step13
import numpy as np
from steps.step13 import Variable, square, add

x = Variable(np.array(1.0))
y = Variable(np.array(2.0))

z = add(square(x), square(y))
z.backward()
print(f'x.grad: {x.data}')
print(f'y.grad: {y.grad}')
print(f'z.grad: {z.grad}')

x.grad: 1.0
y.grad: 4.0
z.grad: 1.0


In [6]:
# step14
# 14.2
import numpy as np
from steps.step14 import Variable, square, add
x = Variable(np.array(3.0))
y = add(x, x)
y.backward()
print(f'x.grad: {x.grad}')

x = Variable(np.array(3.0))
y = add(add(x,x),x)
y.backward()
print(f'x.grad: {x.grad}')

x.grad: 2.0
x.grad: 3.0


In [1]:
# 14.3
import numpy as np
from steps.step14 import Variable, square, add
x = Variable(np.array(3.0))
y = add(x, x)
y.backward()
print(f'x.grad: {x.grad}')

y = add(add(x,x),x)
y.backward()
print(f'x.grad: {x.grad}')

x = Variable(np.array(3.0))
y = add(x, x)
y.backward()
print(f'x.grad: {x.grad}')

# cleargrad
x.cleargrad()
y = add(add(x,x),x)
y.backward()
print(f'x.grad: {x.grad}')

x.grad: 2.0
x.grad: 5.0
x.grad: 2.0
x.grad: 3.0


In [2]:
# step15
pass

In [4]:
# step16
pass

In [1]:
# step17
import numpy as np
from steps.step17 import Variable, square, add

for i in range(10):
    x = Variable(np.random.randn(100))
    y = square(square(square(x)))

In [3]:
# step18
# 18.1
import numpy as np
from steps.step18 import Variable, add

x0 = Variable(np.array(1.0))
x1 = Variable(np.array(1.0))

t = add(x0, x1)
y = add(x0, t)
y.backward()
print(y.grad, t.grad)
print(x0.grad, x1.grad)

None None
2.0 1.0


In [11]:
# 18.4
import numpy as np
from steps.step18 import Variable, Config, add, square

Config.enable_backprop = True
x = Variable(np.ones((100, 100, 100)))
y = square(square(x))
y.backward()
print(x.grad[0][0])

Config.enable_backprop = False
x = Variable(np.ones((100, 100, 100)))
y = square(square(x))
print(x.grad) # None

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4.]
None


In [4]:
# 18.5
import numpy as np
from steps.step18 import Variable, Config, add, square, using_config, no_grad

x = Variable(np.array(2.0))
y = square(x)
y.backward()
print(x.grad)

with using_config('enable_backprop', False):
    x = Variable(np.array(2.0))
    y = square(x)
#     y.backward() # raise Error
    
with no_grad():
    x = Variable(np.array(2.0))
    y = square(x)
#     y.backward() # raise Error

4.0


In [10]:
# step19
import numpy as np
from steps.step19 import Variable

x = Variable(np.arange(0,100).reshape(10,10))
print(len(x))
print(x.dtype)
print(x.ndim)
print(x.size)
print(x.shape)
print(x.shape)
print(x)

10
int64
2
100
(10, 10)
(10, 10)
variable( [[ 0  1  2  3  4  5  6  7  8  9]
          [10 11 12 13 14 15 16 17 18 19]
          [20 21 22 23 24 25 26 27 28 29]
          [30 31 32 33 34 35 36 37 38 39]
          [40 41 42 43 44 45 46 47 48 49]
          [50 51 52 53 54 55 56 57 58 59]
          [60 61 62 63 64 65 66 67 68 69]
          [70 71 72 73 74 75 76 77 78 79]
          [80 81 82 83 84 85 86 87 88 89]
          [90 91 92 93 94 95 96 97 98 99]] )


In [5]:
# step20
import numpy as np
from steps.step20 import Variable, mul, add

a = Variable(np.array(3.0))
b = Variable(np.array(2.0))
c = Variable(np.array(1.0))

y = add(mul(a,b),c)
y.backward()

print(y)
print(a.grad, b.grad, c.grad)

variable( 7.0 )
2.0 3.0 1.0


In [1]:
# 20.2
import numpy as np
from steps.step20 import Variable

a = Variable(np.array(3.0))
b = Variable(np.array(2.0))
c = Variable(np.array(1.0))

y = a * b + c
y.backward()
print(y)
print(a.grad, b.grad, c.grad)

variable( 7.0 )
2.0 3.0 1.0


In [1]:
# step21
import numpy as np
from steps.step21 import Variable

x = Variable(np.array(2.0))
y = x + np.array(3.0)
print(y)

variable( 5.0 )


In [1]:
# 21.2
import numpy as np
from steps.step21 import Variable

x = Variable(np.array(2.0))
y = x + 3.0
print(y)

x = Variable(np.array(2.0))
y = 3.0 * x + 1.0
print(y)

x = Variable(np.array([1.0]))
y = np.array([2.0]) + x
print(y)

variable( 5.0 )
variable( 7.0 )
variable( [3.] )


In [1]:
# step22
import numpy as np
from steps.step22 import Variable
x = Variable(np.array(2.0))
y = -x
print(y)

variable( -2.0 )


In [1]:
# 22.2
import numpy as np
from steps.step22 import Variable

x = Variable(np.array(2.0))
print(1.0 - x)
print(x-1)

variable(-1.0)
variable(1.0)


In [1]:
# 22.3
import numpy as np
from steps.step22 import Variable

x = Variable(np.array(2.0))
print(2.0 / x)
print(x / 2)

variable(1.0)
variable(1.0)


In [1]:
# 22.4
import numpy as np
from steps.step22 import Variable

x = Variable(np.array(2.0))
y = x ** 3
print(y)

variable(8.0)


In [3]:
# step23
import numpy as np
from dezero.core_simple import Variable

x = Variable(np.array(1.0))
print(x)

variable(1.0)


In [1]:
# 23.2
import numpy as np
# from dezero.core_simple import Variable
from dezero import Variable

x = Variable(np.array(1.0))
y = (x + 3) ** 2
y.backward()
print(y)
print(x.grad)

variable(16.0)
8.0


In [4]:
# step24
import numpy as np
from dezero import Variable

def sphere(x, y):
    z = x**2 + y**2
    return z

x = Variable(np.array(1.0))
y = Variable(np.array(1.0))
z = sphere(x, y)
z.backward()
print(x.grad, y.grad)

2.0 2.0


In [5]:
# 24.2
def matyas(x,y):
    z = 0.26 * (x ** 2 + y ** 2) - 0.48 * x * y
    return z

x = Variable(np.array(1.0))
y = Variable(np.array(1.0))
z = matyas(x, y)
z.backward()
print(x.grad, y.grad)

0.040000000000000036 0.040000000000000036


In [6]:
# 24.3
def goldstein(x, y):
    z = (1 + (x + y + 1)**2 * (19 - 14*x + 3*x**2 - 14*y + 6*x*y + 3*y**2)) * \
        (30 + (2*x - 3*y)**2 * (18 - 32*x + 12*x**2 + 48*y - 36*x*y + 27*y**2))
    return z

x = Variable(np.array(1.0))
y = Variable(np.array(1.0))
z = goldstein(x, y)
z.backward()
print(x.grad, y.grad)

-5376.0 8064.0
